server:
  port: 8092    
spring:     #定义springmvc视图解析器
  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp

#添加dubbo的配置
dubbo:
  scan:
    basePackages: com.jt
  application:
    name: consumer-web
  registry:
    address: zookeeper://192.168.147.130:2182?backup=192.168.147.130:2183,192.168.147.130:2184
  